<?php

    if (!isset($_GET['message'])) {  // checks if the message parameter exists in the URL
        session_start(); //starts the session
        $message = false; //sets the default value to false when no message is passed
    } else {
        //decode the message for display
        $message = htmlspecialchars(urldecode($_GET['message'])); //retrieves a message and decodes it into something meaningful (something that a user can understand)
    }


    require_once "assets/dbconn.php"; //requires in dbconn for the database connection
    require_once "assets/common.php"; //requires in common for functions


    echo "<!DOCTYPE html>";

        echo "<html lang='en'>"; //sets language to english
        echo "<head>";
            echo "<meta charset='UTF-8'>";
            echo "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"; //meta data
            echo "<link rel='stylesheet' type='text/css' href='assets/styles.css'>"; //links the stylesheet
            echo "<title>Loyalty Scheme - Greenfield Local Hub</title>"; //puts a title on the tab of the page
        echo "</head>";

        echo "<body>";

            require "assets/header.php"; //requires the header for the page to load

                // this was generated by ecosia ai as placeholder text and an easy diagram of a basic loyalty scheme for glh.

            echo '<section id="loyalty-scheme">';
            echo '<h1>Greenfield Local Hub Loyalty Scheme</h1>';
            echo '<p><strong>Welcome to our Loyalty Program!</strong><br>';
            echo 'Earn rewards every time you shop with us.</p>';

            echo '<h2>How It Works:</h2>';
            echo '<ul>';
            echo '<li><strong>Earn 1 Point for Every £1 Spent</strong><br>';
            echo 'Every pound you spend earns you 1 loyalty point.</li>';
            echo '<li><strong>Collect Points &amp; Redeem Rewards</strong>';
            echo '<ul>';
            echo '<li>50 points = £5 off your next purchase</li>';
            echo '<li>100 points = £10 off or a free product (up to £10 value)</li>';
            echo '<li>200 points = £25 off or exclusive VIP offer</li>';
            echo '</ul>';
            echo '</li>';
            echo '<li><strong>Bonus Points</strong>';
            echo '<ul>';
            echo '<li>Sign up bonus: 10 points</li>';
            echo '<li>Birthday bonus: 20 points</li>';
            echo '<li>Special promotions: Double points days</li>';
            echo '</ul>';
            echo '</li>';
            echo '</ul>';

            echo '<h2>How to Join:</h2>';
            echo '<p>Sign up in-store or online with your email and phone number.<br>';
            echo 'Show your loyalty card or app at checkout to collect points.</p>';

            echo '<h2>Terms &amp; Conditions:</h2>';
            echo '<ul>';
            echo '<li>Points are non-transferable and cannot be exchanged for cash</li>';
            echo '<li>Points expire after 12 months of inactivity</li>';
            echo '<li>Rewards cannot be combined with other discounts or promotions</li>';
            echo '<li>[Include any other shop-specific rules]</li>';
            echo '</ul>';

            echo '<p><em>Thank you for being a valued customer!</em><br>';
            echo '[Shop Contact Info &amp; Social Media]</p>';
            echo '</section>';


            echo user_message();

            try {
                echo "";
            } catch (PDOException $e) {
                echo $e->getMessage();
            }

            require "assets/footer.php"; //requires the footer for the page to load

        echo "</body>";

    echo "</html>";


    if (!$message) {
        echo user_message();  // runs the user message function if the message variable is empty
    } else {
        echo $message;
    }